# Generated by Django 3.0.6 on 2020-11-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doe', models.CharField(max_length=50)),
                ('noBunnies', models.PositiveIntegerField()),
                ('noMale', models.PositiveIntegerField()),
                ('noFemales', models.PositiveIntegerField()),
                ('noDeaths', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('medication', models.TextField(null=True)),
                ('signs', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(choices=[('feed', 'feed'), ('medication', 'med')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000, null=True)),
                ('seller', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('tagId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('breed', models.CharField(max_length=20, null=True)),
                ('weight', models.FloatField()),
                ('birthLot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bunny', to='rabbits.BirthLot')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('customer', models.CharField(max_length=250, null=True)),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='rabbits.Rabbit')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('treated', models.BooleanField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis', to='rabbits.Disease')),
                ('rabbit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis', to='rabbits.Rabbit')),
            ],
        ),
        migrations.AddField(
            model_name='birthlot',
            name='buck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='rabbits.Rabbit'),
        ),
    ]
