# Generated by Django 3.0.6 on 2020-11-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='seller',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='birthLot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bunny', to='rabbits.BirthLot'),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='breed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
