# Generated by Django 3.0.6 on 2020-11-17 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0002_auto_20201117_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthlot',
            name='buck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='father_of', to='rabbits.Rabbit'),
        ),
        migrations.AlterField(
            model_name='birthlot',
            name='doe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mother_of', to='rabbits.Rabbit'),
        ),
    ]
