# Generated by Django 3.0.6 on 2020-11-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0005_disease_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='signs',
        ),
    ]
