# Generated by Django 3.0.6 on 2020-11-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0006_remove_disease_signs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
